<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net4.8</TargetFramework>
        <OutputType>WinExe</OutputType>
        <OutputPath>..\_Build\$(Configuration)\</OutputPath>
        <ApplicationIcon>..\gear_wheel.ico</ApplicationIcon>
        <ApplicationVersion>0.0.7</ApplicationVersion>
        <StartupObject>Arcas.Program</StartupObject>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <ApplicationVersion>$(ApplicationVersion)-dev</ApplicationVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Include="app.config" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Arcas.UI\Arcas.UI.csproj" />
    </ItemGroup>

    <Target Name="BeforeCompile">

        <PropertyGroup>
            <ApplicationVersion Condition=" $(ApplicationVersion) == ''">$([System.DateTime]::Now.Year).$([System.DateTime]::Today.ToString("MMdd")).$([System.DateTime]::Now.Hour).$([System.DateTime]::Now.Minute)</ApplicationVersion>
        </PropertyGroup>

        <Message Text="------- Application version $(ApplicationVersion)" Importance="High" />

        <Error Condition="'$(ApplicationVersion)' == ''" Text="Необходимо заполнить свойство ApplicationVersion!" />

        <!--<PropertyGroup Condition=" '$(ApplicationVersion.Split(`.`)[0])' == '0' ">
            <VerAssembly>0.1.0.0</VerAssembly>
        </PropertyGroup>

        <PropertyGroup Condition=" '$(ApplicationVersion.Split(`.`)[0])' != '0' ">
            <VerAssembly>$(ApplicationVersion.Split(`.`, StringSplitOptions.None)[0]).0.0.0</VerAssembly>
        </PropertyGroup>

        <PropertyGroup>
            <VerFile>$(VerAssembly.Split(`.`)[0])$([System.DateTime]::Now.Tostring(".yyyy.MM.dd"))</VerFile>
        </PropertyGroup>

        <ItemGroup>
            <AssemblyAttributes Include="AssemblyVersion">
                <_Parameter1>$(VerAssembly)</_Parameter1>
            </AssemblyAttributes>
            <AssemblyAttributes Include="AssemblyFileVersion">
                <_Parameter1>$(VerFile)</_Parameter1>
            </AssemblyAttributes>
            <AssemblyAttributes Include="AssemblyInformationalVersion">
                <_Parameter1>$(ApplicationVersion)</_Parameter1>
            </AssemblyAttributes>
        </ItemGroup>
        <WriteCodeFragment Language="C#" OutputFile="$(BaseIntermediateOutputPath)/AssemblyVer.cs" AssemblyAttributes="@(AssemblyAttributes)" />
        <ItemGroup>
            <Compile Include="$(BaseIntermediateOutputPath)/AssemblyVer.cs" />
        </ItemGroup>-->
    </Target>

    <Target Name="ZippedOutput" AfterTargets="Build">
        <ItemGroup Condition="'$(Configuration)' != 'Release'">
            <ResFiles Include="$(OutputPath)*.*" />
        </ItemGroup>
        <ItemGroup Condition="'$(Configuration)' == 'Release'">
            <ResFiles Include="$(OutputPath)*.*" Exclude="**\*.pdb" />
        </ItemGroup>
        <PropertyGroup>
            <ZippedDir>$(OutputPath)..\zipDir</ZippedDir>
        </PropertyGroup>
        <Message Text="------- Zipped" Importance="High" />
        <RemoveDir Directories="$(ZippedDir)" />
        <Copy SourceFiles="@(ResFiles)" DestinationFolder="$(ZippedDir)" />
        <ZipDirectory SourceDirectory="$(ZippedDir)" DestinationFile="$(OutputPath)\..\$(AssemblyName)_$(ApplicationVersion).zip" Overwrite="true" />
    </Target>
</Project>