<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net4.8</TargetFramework>
        <OutputPath>..\_Build\$(Configuration)\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cav.Core" Version="8.11.2" />
        <PackageReference Include="Cav.WinForms" Version="5.1.0" />
        <PackageReference Include="Autoupdater.NET.Official" Version="*" />
        <!--<PackageReference Include="Microsoft.TeamFoundationServer.ExtendedClient" Version="*" />-->
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.TeamFoundation.Client">
            <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Client.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.TeamFoundation.ProjectManagement">
            <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.ProjectManagement.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.TeamFoundation.VersionControl.Client">
            <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.VersionControl.Client.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.TeamFoundation.VersionControl.Common">
            <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.VersionControl.Common.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.TeamFoundation.VersionControl.Controls">
            <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.VersionControl.Controls.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.TeamFoundation.WorkItemTracking.Client">
            <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.WorkItemTracking.Client.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
            <Private>False</Private>
        </Reference>

        <Reference Include="System.ServiceModel" />
        <Reference Include="System.Web.Services" />
    </ItemGroup>

</Project>