<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net4.8</TargetFramework>
        <OutputPath>..\_Build\$(Configuration)\</OutputPath>
        <RootNamespace>Arcas</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cav.Core" Version="8.11.2" />
        <PackageReference Include="Cav.WinForms" Version="5.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Arcas.BL\Arcas.BL.csproj" />
    </ItemGroup>

</Project>
